import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@in-need-of-time/utils";
import { Providers } from "@/components/Providers";
import Header from "@/components/Header";
import { Footer } from "@/components/Footer";
import "./globals.css";
import { TooltipProvider, Toaster } from "@in-need-of-time/ui";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-background min-h-[100dvh] font-sans antialiased", fontSans.variable)}>
        <Providers>
          <TooltipProvider>
            <Toaster />
            <Header />
            {children}
          </TooltipProvider>
        </Providers>
      </body>
    </html>
  );
}
